apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ctfplatform.org.com
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlp6Q0NBUTBDQVFBd0hqRWNNQm9HQTFVRUF4TVRZM1JtY0d4aGRHWnZjbTB1YjNKbkxtTnZiVEJaTUJNRwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk5lZGFJSEN4TzhmWldsMGxReEhtZW5IcVBYLzRDTC9WcDZnClFWeXZzODlBdnJSb1gwQWJ5QUQxNURWbE9EbFpwRWd1WTd6WVZnQ2xKWTJpQkM5eU03NmdnWXd3Z1lrR0NTcUcKU0liM0RRRUpEakY4TUhvd2VBWURWUjBSQkhFd2I0SVRZM1JtY0d4aGRHWnZjbTB1YjNKbkxtTnZiWUljY21WbgphWE4wY25rdVkzUm1jR3hoZEdadmNtMHViM0puTG1OdmJZSVpabXhoYzJzdVkzUm1jR3hoZEdadmNtMHViM0puCkxtTnZiWUlmWTJoaGNuUnRkWE5sZFcwdVkzUm1jR3hoZEdadmNtMHViM0puTG1OdmJUQUtCZ2dxaGtqT1BRUUQKQWdOSUFEQkZBaUVBb3Naa3FVaEJOQ1VtTzF2R2hqem96S2R0TDh0WWsxbnlnTHJPbE1rcUJTQUNJQ2dYdmNuNgphNWFUVDEzZSswUEYwTzBTUFgzcG1Sa1dSeFl2dkQwOWx0UVYKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - server auth


