apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-web-crimemail-deployment
  namespace: ctfspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-web-crimemail
  template:
    metadata:
      labels:
        app: ctf-web-crimemail
    spec:
      containers:
      - name: ctf-web-crimemail
        image: liviubanica/ctf-crimemail
        ports:
        - containerPort: 80
