#apiVersion: v1
#kind: Namespace
#metadata:
#  name: ctfspace
#  labels:
#    name: ctfspace
    
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
  namespace: ctfspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: ctfplatformsa
      containers:
      - name: flask
        image: liviubanica/licent_flask:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8089
        resources:
          limits:
            cpu: 1500m
            memory: 1Gi
          requests:
            cpu: 712m
            memory: 712Mi
      # imagePullSecrets:
      # - name: registry-credentials
