apiVersion: apps/v1
kind: Deployment
metadata:
    name: ctf-jailed-jail-deployment
    labels:
        component: jail
spec:
    replicas: 5
    selector:
        matchLabels:
            component: jail
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                component: jail
        spec:
            containers:
                - name: jail
                  image: liviubanica/ctf-jailed-jail:1
                  securityContext:
                      privileged: true
