apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.deployment.name }}"
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Values.deployment.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deployment.name }}"
    spec:
      containers:
      - name: "{{ .Values.deployment.name }}"
        image: "{{ .Values.deployment.imageName }}"
        ports:
        - containerPort: {{ .Values.deployment.port }}
        securityContext:
          privileged: false
        resources: {}
