apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: registryrepository
          image: {{ .Values.deployment.imageName}}
          ports:
            - containerPort: 5000
          env:
            - name: STORAGE
              value: local
            - name: STORAGE_LOCAL_ROOTDIR
              value: /imageregistry
            - name: NGINX_MAX_REQUEST_BODY_SIZE
              value: "{{ .Values.nginx.maxRequestBodySize }}"
          volumeMounts:
            - name: registryrepository-storage
              mountPath: /imageregistry
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 712m
              memory: 712Mi
      volumes:
        - name: registryrepository-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
