apiVersion: v1
clusters:
- cluster:
    certificate-authority: certs/kubeCA/ca.crt
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: ctfspace
    user: ctfplatformsa
  name: ctfplatformsa-minikube
current-context: ctfplatformsa-minikube
kind: Config
preferences: {}
users:
- name: ctfplatformsa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkFudm12WWVmN1g0YV94Z1lwUFZTMFN2a2ozU3BIUGR0QU9peHcyVUNGZ3MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjdGZzcGFjZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjdGZwbGF0Zm9ybS1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiY3RmcGxhdGZvcm1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjM2ZjZlNzU1LWE2MTQtNDBhYS1iOTQxLTljNzE0NDVlYWYxMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjdGZzcGFjZTpjdGZwbGF0Zm9ybXNhIn0.mTixKK-_Jk6DymZw2haHoA1oG4PVrRYuv4PZxoIpYtCWTFfIbF9YJQGlm4DoW3c7nSVAkH5r4dAwAZE1SfEsOpyGkw3uf_v-NhDtzB9C25VTARPemRYMy7h3cO0wTCVjrCOIs_-8f9ZHpljpnlI2jnPyNp35x3TvUeKwM2gg2hgXxLxNVDhrUqsSR9eTY9vV29QcXBnGZGbZkbVXNvi8ZD9-IIjAy1VGe9_jlK1bODFfnakP0wjOrg1NzfMTEL_2KDaQrQ3GqYqM5eVXBPc1TRJ4FWwUbXgsckPlyX45p5t3PkWgyxQkHumw9bqPAsOYAUWCM0V4tq2yEyCwxgfnWA

